[package]
name = "flash-lso"
version = "0.5.0"
authors = ["CUB3D <callumthom11@gmail.com>"]
description = "Fast and safe SOL/AMF0/AMF3 parsing. Supports serde, Adobe flex and cyclic references"
repository = "https://github.com/CUB3D/rust-sol"
readme = "README.md"
license = "MIT"
keywords = ["sol", "amf", "parser", "serializer", "flash"]
edition = "2021"
categories = ["data-structures", "encoding", "parser-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
cookie-factory = "0.3.2"
derive-try-from-primitive = "1.0.0"
enumset = { version = "1.0.8", features = ["serde"] }
thiserror = "1.0.30"
serde = { version = "1.0.133", optional = true, features = ["derive", "rc"] }

[dev-dependencies]
pretty_assertions = "1.0.0"
serde_json = "1.0.74"
criterion = "0.3.5"

[[bench]]
name = "benchmarks"
harness = false

[features]
default = []
flex = []
all = ["serde", "flex"]
